[package]
name = "midatopay_starknet"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.12.0, <3.0.0"

# OpenZeppelin (usando repo local)
openzeppelin_access = { path = "../../cairo-contracts/packages/access" }
openzeppelin_introspection = { path = "../../cairo-contracts/packages/introspection" }
openzeppelin_security = { path = "../../cairo-contracts/packages/security" }
openzeppelin_token = { path = "../../cairo-contracts/packages/token" }

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"
build = "scarb build"
